import toml from "toml";
import fs from "fs";
import { marked } from "marked";

const WARNING = "// DO NOT EDIT this file, it is machine generated\n";

function loadMDfiles(dir: string): {
  [key: string]: { [key: string]: string };
} {
  let pages: { [key: string]: { [key: string]: string } } = {};
  fs.globSync(`${dir}**/*.md`).forEach((m: string) => {
    const [page, lang] = m
      .slice(m.lastIndexOf("/") + 1, m.length - 3)
      .split(".");
    if (!pages[page]) {
      pages[page] = {};
    }
    pages[page][lang] = marked.parse(
      fs.readFileSync(m, { encoding: "utf-8" }),
      {
        async: false,
        gfm: true,
      },
    );
  });
  return pages;
}

function loadTOMLfiles(dir: string): {
  [key: string]: { [key: string]: string };
} {
  let strings: { [key: string]: { [key: string]: string } } = {};
  fs.globSync(`${dir}**/*.toml`).forEach((m: string) => {
    const lang = m.slice(m.lastIndexOf("/") + 1, m.length - 5);
    Object.entries(
      toml.parse(fs.readFileSync(m, { encoding: "utf-8" })),
    ).forEach(([k, v]) => {
      if (!(k in strings)) {
        strings[k] = {};
      }
      strings[k][lang] = String(v);
    });
  });
  return strings;
}

function parsePages(inDir: string, outFile: string) {
  const f = loadMDfiles(inDir);
  fs.writeFile(
    outFile,
    WARNING +
      "export const pages: { [key: string]: { [key: string]: string } } = " +
      JSON.stringify(f, undefined, 2),
    (err) => {
      if (err) throw err;
    },
  );
}

function parseStrings(inDir: string, outFile: string) {
  const f = loadTOMLfiles(inDir);
  fs.writeFile(
    outFile,
    WARNING +
      "export const strings: { [key: string]: { [key: string]: string } } = " +
      JSON.stringify(f, undefined, 2),
    (err) => {
      if (err) throw err;
    },
  );
}

function appendSlash(dir: string | undefined) {
  if (!dir) {
    return dir;
  }
  return dir[-1] == "/" ? dir : dir + "/";
}

function main() {
  const args = process.argv.slice(2);
  let inDir = appendSlash(
    args.find((a) => a.startsWith("--in-dir="))?.slice("--in-dir=".length),
  );
  let outDir = appendSlash(
    args.find((a) => a.startsWith("--out-dir="))?.slice("--out-dir=".length),
  );

  if (!inDir || !outDir) {
    throw Error();
  }

  parseStrings(inDir + "strings/", outDir + "strings.ts");
  parsePages(inDir + "pages/", outDir + "pages.ts");
}

main();
