_language_endonym = "english"
abm_long = "alcohol by mass (%mass)"
abm_short = "ABM"
abm_meas_long = "alcohol by mass (%mass) as measured by a glass alcoholmeter"
abm_meas_short = "ABM<sub><i>meas</i></sub>"
abv_long = "alcohol by volume (%vol)"
abv_short = "ABV"
abv_20C_short = "ABV<sub><i>legal</i></sub>"
abv_20C_long = "alcohol by volume (%vol) as legally defined"
abv_meas_long = "alcohol by volume (%vol) as measured by a glass alcoholmeter"
abv_meas_short = "ABV<sub><i>meas</i></sub>"
compiling_calculator = "compiling calculator"
computing = "computing"
delete = "delete"
deleteQuestion = "delete?"
dens_long = "density (g/L)"
dens_short = "dens"
dens_20C_short = "dens<sub><i>20°C</i></sub>"
dens_meas_long = "density (g/L) as measured by a glass areometer"
dens_meas_short = "dens<sub><i>meas</i></sub>"
fold = "fold"
glass_exp_coeff = "glass expansion coefficient"
glass_soda_lime_name = "soda–lime glass"
glass_soda_lime_desc = "also called 'ordinary glass'"
glass_borosilicate_name = "borosilicate glass"
glass_borosilicate_desc = "known under the trade name Pyrex"
glass_no_correction_name = "without correction"
glass_no_correction_desc = "apply no correction (such as for electronic instruments)"
help = "help"
kpa_long = "kilograms of pure alcohol (kg)"
kpa_short = "KPA"
kpa_20C_short = "KPA"
language = "language"
lpa_long = "liters of pure alcohol (L)"
lpa_short = "LPA"
lpa_20C_short = "LPA"
mass_long = "mass (kg)"
mass_short = "mass"
model = "model"
model_bettin_spieweck_desc = "An update to the Wagenbreth polynomial to simplify it and use the new ITS-1990 standard. Subtly incompatible with OIML R22."
model_naive_linear_desc = "This model assumes the change in density is linear with respect to the alcohol quantity. For demonstration purposes only!"
model_oiml_r22_desc = "Published by OIML recommendation 22 in 1975. Legally mandated in many countries."
oiml_tables = "OIML tables"
parameters_model = "model parameters"
parameters_ui = "interface parameters"
result = "result"
select_a_table = "select a table to display"
settings = "settings"
temp_long = "temperature (°C)"
temp_short = "temp"
unfold = "unfold"
vol_long = "volume (L)"
vol_short = "vol"
vol_20C_long = "volume (L) this would have at 20°C"
vol_20C_short = "vol<sub><i>20°C</i></sub>"
vol_meas_long = "volume (L) at the current temperature"
vol_meas_short = "vol"
