_language_endonym = "français"
":" = " :"
abm_long = "taux d'alcool massique (%mas)"
abm_short = "TAM"
abm_meas_long = "taux d'alcool massique (%mas) tel que mesuré par un alcoomètre en verre"
abm_meas_short = "TAM<sub><i>mes</i></sub>"
abv_long = "taux d'alcool volumique (%vol)"
abv_short = "TAV"
abv_20C_short = "TAV<sub><i>légal</i></sub>"
abv_20C_long = "taux d'alcool volumique (%vol) tel que légalement défini"
abv_meas_long = "taux d'alcool volumique (%vol) tel que mesuré par un alcoomètre en verre"
abv_meas_short = "TAV<sub><i>mes</i></sub>"
compiling_calculator = "calcul de compilation"
computing = "calcul"
delete = "supprimer"
deleteQuestion = "supprimer ?"
dens_long = "densité (g/L)"
dens_short = "dens"
dens_20C_short = "dens<sub><i>20°C</i></sub>"
dens_meas_long = "densité (g/L) telle que mesurée par un aréomètre en verre"
dens_meas_short = "dens<sub><i>mes</i></sub>"
fold = "replier"
glass_exp_coeff = "coefficient d'expansion du verre"
glass_soda_lime_name = "verre sodocalcique"
glass_soda_lime_desc = "aussi appellé « verre ordinaire »"
glass_borosilicate_name = "verre borosilicate"
glass_borosilicate_desc = "connu à travers la marque Pyrex"
glass_no_correction_name = "sans correction"
glass_no_correction_desc = "ne pas appliquer de correction (par exemple pour les instruments électroniques)"
help = "aide"
kpa_long = "kilogrammes d'alcool pur (kg)"
kpa_short = "KAP"
kpa_20C_short = "KAP"
language = "langue"
lpa_long = "litres d'alcool pur (L)"
lpa_short = "LAP"
lpa_20C_short = "LAP"
mass_long = "masse (kg)"
mass_short = "mass"
model = "modèle"
model_details = "à propos de ce modèle"
model_bettin_spieweck_desc = "Une mise à jour du polynome de Wagenbreth, plus simple et utilisant le nouveau standard ITS-1990. Légèrement incompatible avec le modèle OIML R22."
model_gay_lussac_1824_desc = "Une reconstruction du tout premier modèle d'alcoométrie à relier le TAV à la densité et la température. Faux de plusieurs manières."
model_naive_linear_desc = "Ce modèle suppose que la densité évolue linéairement par rapport à la quantité d'alcool. À valeur éducative uniquement!"
model_oiml_r22_desc = "Publié par l'OIML dans sa recommendation 22 en 1975. A valeur légale dans de nombreux pays."
oiml_tables = "tables OIML"
parameters_model = "paramètres du modèle"
parameters_ui = "paramètres de l'interface"
result = "résultat"
select_a_table = "selectionnez une table à afficher"
settings = "Paramètres"
temp_long = "température (°C)"
temp_short = "temp"
temps = "températures"
unfold = "déplier"
vol_long = "volume (L)"
vol_short = "vol"
vol_20C_long = "volume (L) que ce melange aurait à 20°C"
vol_20C_short = "vol<sub><i>20°C</i></sub>"
vol_meas_long = "volume (L) à la température courante"
vol_meas_short = "vol"